[package]
name = "sim_connect_rs"
version = "0.5.3"
edition = "2021"
license-file = "./LICENSE"
repository = "https://github.com/dbidwell94/simconnect_rs"
homepage = "https://github.com/dbidwell94/simconnect_rs"

[lib]

[features]
derive = []
async = []
static_link = ["sim_connect_bindings/static_link"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.70" }
sim_connect_macros = { version = "*", path = "./sim_connect_macros" }
sim_connect_bindings = { version = "*", path = "./sim_connect_bindings" }
sim_connect_data = { version = "*", path = "./sim_connect_data" }
