[package]
name = "msfs-econoworld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_json = { version = "1.0.95" }
reqwest = { version = "0.11.16" }
anyhow = { version = "1.0.70" }
num_enum = { version = "0.6.0" }
semver = { version = "1.0.17" }

[build-dependencies]
bindgen = { version = "0.64.0" }